language: ruby
rvm:
  - 1.9.3
script:
  - bundle exec rake db:setup RAILS_ENV=test
  - bundle exec rake test
before_script:
  - cp config/configuration.yml.dist config/configuration.yml
  - cp config/database.yml.travis config/database.yml
  - cp config/application.yml.dist config/application.yml
  - cp config/mailers.yml.dist config/mailers.yml 
  - psql -c 'create database befdata_test;' -U postgres
